# -*- coding: utf-8 -*-
"""5 - FUNÇÕES EM PYTHON

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16HXFViccfhhkArIIgAIPbDt_yfAzk-lI

Questão 1
"""

def padrao(n):
    for i in range(1, n + 1):
        linha = " ".join([str(i)] * i)
        print(linha)

numero_usuario = int(input("Digite um número inteiro: "))
padrao(numero_usuario)

"""Questão 2"""

def verifica_primo(numero):
    if numero < 2:
        return False
    for i in range(2, int(numero**0.5) + 1):
        if numero % i == 0:
            return False
    return True

numero_usuario_primo = int(input("Digite um número para verificar se é primo: "))

if verifica_primo(numero_usuario_primo):
    print(f"{numero_usuario_primo} é um número primo.")
else:
    print(f"{numero_usuario_primo} não é um número primo.")

"""Questão 4"""

def inverte_string(s):
    return s[::-1]

entrada = input("Digite uma frase: ")
saida = inverte_string(entrada)

print("Frase Invertida:", saida)

"""Questão 5"""

def maior_valor():
    maiornumero = None

    for i in range(5):
        numero = int(input(f"Digite o {i + 1}º número: "))

        if maiornumero is None or numero > maiornumero:
            maiornumero = numero

    print(f"O maior número digitado é: {maiornumero}")

maior_valor()

"""Questão 6"""

def conta_vogais(frase):
    vogais = "aeiouAEIOU"
    contador = 0

    for char in frase:
        if char in vogais:
            contador += 1

    return contador

frase_usuario = input("Digite uma frase: ")
numero_vogais = conta_vogais(frase_usuario)

print(f"O número de vogais na frase é: {numero_vogais}")

"""Questão 7"""

def soma_quadrados(lista_numeros):
    soma = 0
    for numero in lista_numeros:
        soma += numero ** 2
    return soma

numeros = [1, 2, 3, 4, 5]
resultado = soma_quadrados(numeros)
print(f"A soma dos quadrados dos números é: {resultado}")

"""Questão 8"""

def imprime_tabuada(numero):
    for i in range(1, 11):
        resultado = numero * i
        print(f"{numero} x {i} = {resultado}")

numero_digitado = int(input("Digite um número inteiro: "))
imprime_tabuada(numero_digitado)